// Foto-Challenges für die Party. Jede Aufgabe = ein Foto mit jemandem/etwas.
// Ziel: die Gemeinschaft stärken, verbinden, Spaß haben — niemanden bloßstellen.
// Jede Aufgabe hat eine Kategorie (cat) und einen Text (text).

export const TASKS = [
  // — Der Klassiker —
  { cat: 'Der Klassiker', text: 'Finde jemanden, den du noch nicht kennst, und posiert zusammen wie Rockstars.' },
  { cat: 'Der Klassiker', text: 'Macht ein klassisches Gruppenfoto zu dritt – Arme umeinander, breites Grinsen.' },
  { cat: 'Der Klassiker', text: 'Findet die perfekte Ecke für ein gemeinsames Selfie mit mindestens vier Leuten.' },
  { cat: 'Der Klassiker', text: 'Macht ein Foto, auf dem alle in die Luft springen – gleichzeitig!' },
  { cat: 'Der Klassiker', text: 'Stellt ein berühmtes Albumcover zu zweit nach.' },
  { cat: 'Der Klassiker', text: 'Findet jemanden für ein feierliches Anstoßen und haltet den Moment fest.' },
  { cat: 'Der Klassiker', text: 'Baut eine kleine Menschenpyramide (sitzend zählt auch!) und lasst euch ablichten.' },
  { cat: 'Der Klassiker', text: 'Zwei Personen tragen eine dritte huckepack – festhalten!' },
  { cat: 'Der Klassiker', text: 'Stellt eine berühmte Filmszene nach, die alle sofort erkennen.' },
  { cat: 'Der Klassiker', text: 'Findet fünf Leute für ein Foto im Kreis, alle Köpfe zur Mitte geneigt.' },
  { cat: 'Der Klassiker', text: 'Macht ein Fußball-Team-Jubelfoto, als hättet ihr gerade ein Tor geschossen.' },
  { cat: 'Der Klassiker', text: 'Baut eine Reihe wie ein Sportteam vorm Anpfiff und grinst in die Kamera.' },
  { cat: 'Der Klassiker', text: 'Macht ein Rücken-an-Rücken-Foto wie auf einem Actionfilm-Poster.' },
  { cat: 'Der Klassiker', text: 'Stellt zu dritt das Cover eines Magazins nach – einer hält ein imaginäres Mikro.' },
  { cat: 'Der Klassiker', text: 'Findet einen Spiegel und macht ein Spiegel-Selfie mit mindestens zwei Leuten.' },
  { cat: 'Der Klassiker', text: 'Macht ein Foto, bei dem alle in dieselbe Richtung schauen – nur einer blickt in die Kamera.' },
  { cat: 'Der Klassiker', text: 'Stellt eine altmodische Familienfoto-Pose nach, steif und ernst – dann alle lachen lassen.' },
  { cat: 'Der Klassiker', text: 'Findet die größte Gruppe, die noch aufs Foto passt, und zählt laut mit.' },

  // — Der Zufall —
  { cat: 'Der Zufall', text: 'Finde jemanden, der im selben Monat Geburtstag hat wie du. Gratuliert euch gegenseitig.' },
  { cat: 'Der Zufall', text: 'Finde jemanden mit denselben Anfangsbuchstaben im Vornamen wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der genauso große (oder kleine) Schuhe trägt wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der im selben Sternzeichen geboren ist wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der aus demselben Ort kommt oder dort schon mal gewohnt hat.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der dasselbe Lieblingsgetränk hat wie du. Prost!' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der heute dasselbe Verkehrsmittel benutzt hat wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden mit derselben Augenfarbe wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der denselben Beruf hat oder dasselbe studiert wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der heute ungefähr zur gleichen Uhrzeit aufgestanden ist wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden mit derselben Anzahl an Geschwistern wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der denselben Vornamen wie ein Familienmitglied von dir trägt.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der schon mal im selben Land im Urlaub war wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden mit derselben Lieblingsjahreszeit wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der dieselbe Anzahl an Haustieren hat (oder hatte) wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der genauso oft schon auf einer Hochzeit war wie du.' },
  { cat: 'Der Zufall', text: 'Finde jemanden mit demselben Lieblingsfach aus der Schulzeit.' },
  { cat: 'Der Zufall', text: 'Finde jemanden, der dasselbe Betriebssystem auf dem Handy nutzt wie du.' },

  // — Das Outfit —
  { cat: 'Das Outfit', text: 'Finde jemanden, der etwas in deiner Lieblingsfarbe trägt. Zeigt stolz auf die Kleidung.' },
  { cat: 'Das Outfit', text: 'Finde jemanden mit den coolsten Schuhen des Abends und fotografiert sie zusammen.' },
  { cat: 'Das Outfit', text: 'Finde zwei Leute, die zufällig etwas Ähnliches tragen – Partnerlook!' },
  { cat: 'Das Outfit', text: 'Finde jemanden mit einem auffälligen Accessoire (Hut, Kette, Brille) und posiert damit.' },
  { cat: 'Das Outfit', text: 'Tauscht für ein Foto ein Kleidungsstück oder Accessoire miteinander.' },
  { cat: 'Das Outfit', text: 'Findet die eleganteste Person im Raum und macht ein Foto auf dem roten Teppich (auch ohne Teppich).' },
  { cat: 'Das Outfit', text: 'Finde jemanden, der Karos, Streifen oder Punkte trägt, und feiert das Muster.' },
  { cat: 'Das Outfit', text: 'Finde jemanden mit demselben Schmuckstück-Typ (Ohrring, Kette, Ring) wie du.' },
  { cat: 'Das Outfit', text: 'Findet die auffälligste Frisur des Abends und lasst sie im Foto glänzen.' },
  { cat: 'Das Outfit', text: 'Finde jemanden mit einer Uhr am Handgelenk und vergleicht die Uhrzeit fürs Foto.' },
  { cat: 'Das Outfit', text: 'Finde zwei Personen mit komplett unterschiedlichem Stil und stellt sie nebeneinander.' },
  { cat: 'Das Outfit', text: 'Finde jemanden, der etwas Selbstgemachtes trägt (Schmuck, Kleidung), und fragt nach der Geschichte dazu.' },
  { cat: 'Das Outfit', text: 'Tauscht für ein Foto die Schuhe – auch wenn sie nicht passen.' },
  { cat: 'Das Outfit', text: 'Findet die längste Kette aus Accessoires, die ihr an einer Person entdeckt, und zählt sie im Bild.' },
  { cat: 'Das Outfit', text: 'Finde jemanden mit Hut oder Mütze und tauscht kurz die Kopfbedeckung fürs Foto.' },
  { cat: 'Das Outfit', text: 'Findet zwei Personen in derselben Farbfamilie (nicht identisch, aber ähnlich) und stellt einen Farbverlauf nach.' },
  { cat: 'Das Outfit', text: 'Finde die Person mit dem coolsten Outfit-Detail aus zweiter Hand (Vintage, geerbt, geliehen) und hört die Geschichte dazu.' },

  // — Das Talent —
  { cat: 'Das Talent', text: 'Finde jemanden mit einem versteckten Talent und haltet es im Bild fest.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der jonglieren, pfeifen oder eine Grimasse ziehen kann – Beweisfoto!' },
  { cat: 'Das Talent', text: 'Findet jemanden, der einen kleinen Tanzschritt zeigt, und tanzt mit.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der ein Tier täuschend echt imitieren kann. Macht das Foto im Moment.' },
  { cat: 'Das Talent', text: 'Findet jemanden, der die Zunge rollen oder mit den Ohren wackeln kann.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der euch einen Zaubertrick zeigt, und fangt die Überraschung ein.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der ein Gedicht oder einen Zungenbrecher aufsagen kann.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der rückwärts zählen kann, während er balanciert.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der mit geschlossenen Augen deine Nase treffen kann.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der einen Akzent nachmachen kann, und lasst ihn kurz auftreten.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der pfeifen und gleichzeitig tanzen kann.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der einen Karten- oder Fingertrick kennt.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der ein Tier-Geräusch perfekt imitieren kann.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der einen Zungenbrecher schnell sprechen kann, ohne sich zu verhaspeln.' },
  { cat: 'Das Talent', text: 'Finde jemanden, der euch eine Mini-Choreografie beibringt – nachmachen und festhalten.' },

  // — Die Crew —
  { cat: 'Die Crew', text: 'Sammelt alle mit derselben Haarfarbe wie du für ein Team-Foto.' },
  { cat: 'Die Crew', text: 'Findet alle, die heute zum ersten Mal hier sind, und macht ein Neulings-Foto.' },
  { cat: 'Die Crew', text: 'Bildet eine Kette aus Händen mit mindestens fünf Leuten und fotografiert sie.' },
  { cat: 'Die Crew', text: 'Findet drei Leute, die dasselbe Hobby haben wie du.' },
  { cat: 'Die Crew', text: 'Versammelt alle, die schon einmal gemeinsam gereist sind, für ein Erinnerungsfoto.' },
  { cat: 'Die Crew', text: 'Bildet die längste Menschenreihe, die ihr auf ein Foto bekommt.' },
  { cat: 'Die Crew', text: 'Sammelt alle, die heute mit demselben Verkehrsmittel angereist sind.' },
  { cat: 'Die Crew', text: 'Findet alle mit demselben Sternzeichen-Monat und bildet eine kleine Truppe.' },
  { cat: 'Die Crew', text: 'Bildet eine Gruppe aus allen, die schon mal zusammen auf einer anderen Feier waren.' },
  { cat: 'Die Crew', text: 'Sammelt alle mit Brille für ein „Durchblicker“-Gruppenfoto.' },
  { cat: 'Die Crew', text: 'Findet die Crew, die gemeinsam angereist ist, und macht ein Ankunfts-Foto.' },
  { cat: 'Die Crew', text: 'Bildet ein Team aus den lautesten Fans des Abends.' },
  { cat: 'Die Crew', text: 'Versammelt alle mit demselben Vornamen-Anfangsbuchstaben zu einer Buchstaben-Gang.' },
  { cat: 'Die Crew', text: 'Findet die größte Familien- oder Freundesgruppe im Raum und zählt laut mit für das Foto.' },
  { cat: 'Die Crew', text: 'Bildet einen Kreis aus mindestens sechs Personen und fasst euch an den Schultern.' },
  { cat: 'Die Crew', text: 'Findet zwei Personen, die sich heute zum ersten Mal treffen, und macht ihr Kennenlern-Foto.' },

  // — Die Geste —
  { cat: 'Die Geste', text: 'Mach ein Kompliment und halte das Lächeln der Person im Foto fest.' },
  { cat: 'Die Geste', text: 'Finde jemanden, dem du heute noch nicht Hallo gesagt hast, und begrüßt euch herzlich.' },
  { cat: 'Die Geste', text: 'Umarmt euch zur Begrüßung und lasst den Moment fotografieren.' },
  { cat: 'Die Geste', text: 'Bring jemandem einen Drink oder Snack und haltet die Übergabe im Bild fest.' },
  { cat: 'Die Geste', text: 'Findet jemanden, dem ihr für etwas danken möchtet, und macht ein Dankeschön-Foto.' },
  { cat: 'Die Geste', text: 'Bildet mit den Händen gemeinsam ein Herz und fotografiert es.' },
  { cat: 'Die Geste', text: 'High five mit einer Person, die du heute zum ersten Mal triffst – im richtigen Moment ausgelöst.' },
  { cat: 'Die Geste', text: 'Verschenke ein spontanes Kompliment an eine Person, die du kaum kennst, und haltet die Reaktion fest.' },
  { cat: 'Die Geste', text: 'Bringt jemandem einen Stuhl oder Platz zum Sitzen und haltet die Geste fest.' },
  { cat: 'Die Geste', text: 'Findet jemanden, der Hilfe beim Tragen oder Halten braucht, und packt mit an.' },
  { cat: 'Die Geste', text: 'Stellt jemandem eine neue Person vor und macht ein Vorstellungs-Foto zu dritt.' },
  { cat: 'Die Geste', text: 'Findet jemanden, der allein steht, und holt ihn in die Runde – Foto vom neuen Trio.' },
  { cat: 'Die Geste', text: 'Schenkt jemandem ein Lächeln, das er nicht erwartet – Reaktion einfangen.' },
  { cat: 'Die Geste', text: 'Findet zwei Leute, die schon lange befreundet sind, und lasst euch ihr Geheimnis fürs Zusammenhalten verraten – Foto dazu.' },
  { cat: 'Die Geste', text: 'Fragt jemanden nach seinem Lieblingskompliment und schenkt es ihm für das Foto.' },

  // — Das Detail —
  { cat: 'Das Detail', text: 'Findet zwei Leute mit demselben Getränk und stellt die Gläser nebeneinander.' },
  { cat: 'Das Detail', text: 'Sucht das schönste Detail der Location und stellt euch davor.' },
  { cat: 'Das Detail', text: 'Findet etwas Herzförmiges im Raum und posiert damit.' },
  { cat: 'Das Detail', text: 'Findet die schönsten Blumen oder Deko und macht ein Foto damit.' },
  { cat: 'Das Detail', text: 'Findet jemanden mit einem interessanten Ring oder Armband und rückt es ins Bild.' },
  { cat: 'Das Detail', text: 'Baut aus Dingen auf dem Tisch ein kleines Kunstwerk und fotografiert es mit jemandem.' },
  { cat: 'Das Detail', text: 'Findet das kleinste Detail der Deko und rückt es ganz nah ins Bild.' },
  { cat: 'Das Detail', text: 'Sucht zwei Gläser mit demselben Füllstand und stellt sie wie Zwillinge nebeneinander.' },
  { cat: 'Das Detail', text: 'Sucht die schönste Lichtquelle im Raum (Kerze, Lampe, Lichterkette) und posiert davor.' },
  { cat: 'Das Detail', text: 'Findet ein Detail, das an den Anlass der Feier erinnert, und fotografiert es mit Bezug dazu.' },
  { cat: 'Das Detail', text: 'Baut aus Servietten oder Deko eine kleine Skulptur und lasst jemanden stolz daneben posieren.' },
  { cat: 'Das Detail', text: 'Findet das ungewöhnlichste Getränk auf dem Tisch und stellt es ins Rampenlicht.' },
  { cat: 'Das Detail', text: 'Sucht ein Detail in Gold oder Glitzer und macht ein Glamour-Foto damit.' },
  { cat: 'Das Detail', text: 'Findet zwei Dinge auf dem Tisch, die zufällig zusammenpassen, und arrangiert sie fürs Foto.' },
  { cat: 'Das Detail', text: 'Sucht das gemütlichste Sitzplatz-Detail (Kissen, Decke, Kerze) und macht dort ein Foto.' },

  // — Der Moment —
  { cat: 'Der Moment', text: 'Fangt einen ehrlichen Lachmoment zu zweit ein – erst quatschen, dann auslösen.' },
  { cat: 'Der Moment', text: 'Findet jemanden zum Anstoßen und drückt genau beim „Kling“ ab.' },
  { cat: 'Der Moment', text: 'Haltet den Moment fest, in dem ihr gemeinsam etwas Neues probiert.' },
  { cat: 'Der Moment', text: 'Macht ein Foto mitten im Gespräch – natürlich, nicht gestellt.' },
  { cat: 'Der Moment', text: 'Findet die gemütlichste Ecke der Party und macht dort ein entspanntes Foto zu zweit.' },
  { cat: 'Der Moment', text: 'Fangt einen gemeinsamen Tanzmoment ein.' },
  { cat: 'Der Moment', text: 'Fangt den Moment ein, in dem jemand zum ersten Mal heute richtig lacht.' },
  { cat: 'Der Moment', text: 'Haltet fest, wie zwei Leute sich eine Geschichte erzählen – mitten im Erzählen.' },
  { cat: 'Der Moment', text: 'Fangt einen Moment der Überraschung ein – etwa wenn jemand etwas Unerwartetes hört.' },
  { cat: 'Der Moment', text: 'Haltet den Moment fest, in dem die Musik wechselt und alle reagieren.' },
  { cat: 'Der Moment', text: 'Fangt ein Foto ein, während jemand singt oder mitsummt.' },
  { cat: 'Der Moment', text: 'Haltet einen stillen, ruhigen Moment abseits der Party fest – zu zweit.' },
  { cat: 'Der Moment', text: 'Fangt den Moment ein, in dem ein Drink nachgeschenkt wird.' },
  { cat: 'Der Moment', text: 'Haltet fest, wie jemand herzlich über einen Witz lacht – Timing ist alles.' },
  { cat: 'Der Moment', text: 'Fangt einen Moment gemeinsamer Konzentration ein, etwa bei einem Spiel oder Rätsel.' },
  { cat: 'Der Moment', text: 'Haltet den Moment kurz vor einem herzlichen Lachanfall fest – bevor er richtig losbricht.' },

  // — Die Verbindung —
  { cat: 'Die Verbindung', text: 'Finde jemanden und findet drei Gemeinsamkeiten heraus – dann ein Foto zusammen.' },
  { cat: 'Die Verbindung', text: 'Lass dir von jemandem seinen Lieblingsort auf dem Handy zeigen und macht ein Foto dazu.' },
  { cat: 'Die Verbindung', text: 'Finde die Person, die von am weitesten weg angereist ist, und feiert das im Bild.' },
  { cat: 'Die Verbindung', text: 'Finde jemanden, der ein Instrument spielt, und macht ein Foto mit „Luftinstrument“.' },
  { cat: 'Die Verbindung', text: 'Finde jemanden, der denselben Film liebt wie du, und stellt eine Szene nach.' },
  { cat: 'Die Verbindung', text: 'Finde jemanden mit demselben Lieblingsessen und träumt gemeinsam davon (Foto!).' },
  { cat: 'Die Verbindung', text: 'Lass dir einen Trick oder Life-Hack zeigen und haltet ihn im Bild fest.' },
  { cat: 'Die Verbindung', text: 'Finde jemanden und tauscht die lustigste Anekdote der letzten Woche aus – dann ein Foto.' },
  { cat: 'Die Verbindung', text: 'Finde jemanden, der dieselbe Lieblingsserie schaut wie du, und stellt eine Szene nach.' },
  { cat: 'Die Verbindung', text: 'Finde jemanden mit einer ähnlichen Kindheitserinnerung und erzählt sie euch gegenseitig.' },
  { cat: 'Die Verbindung', text: 'Finde jemanden, mit dem du ein Lieblingswort teilst (Dialekt, Running Gag), und benutzt es fürs Foto.' },
  { cat: 'Die Verbindung', text: 'Finde jemanden, der dich an eine Person aus deinem Leben erinnert, und erklärt warum.' },
  { cat: 'Die Verbindung', text: 'Finde jemanden mit einem ähnlichen Traumreiseziel und plant es kurz gemeinsam (Foto als „Buchung“).' },
  { cat: 'Die Verbindung', text: 'Finde jemanden, der dir spontan ein Kompliment für dein bestes Talent gibt.' },
  { cat: 'Die Verbindung', text: 'Finde jemanden und findet gemeinsam eine Sache, die ihr beide noch nie gemacht habt.' },

  // — Die Stimmung —
  { cat: 'Die Stimmung', text: 'Macht gemeinsam die dramatischste Pose, die euch einfällt.' },
  { cat: 'Die Stimmung', text: 'Findet das beste Licht im Raum und macht dort ein Foto zu zweit.' },
  { cat: 'Die Stimmung', text: 'Zeigt zu dritt drei verschiedene Gefühle auf einem Foto.' },
  { cat: 'Die Stimmung', text: 'Macht ein „So cool sind wir“-Foto mit Sonnenbrille (oder so getan als ob).' },
  { cat: 'Die Stimmung', text: 'Stellt gemeinsam eure Lieblings-Emoji nach.' },
  { cat: 'Die Stimmung', text: 'Findet jemanden für ein „Vorher/Nachher“ – erst ernst, dann albern, in einem Bild-Duo.' },
  { cat: 'Die Stimmung', text: 'Macht ein Foto, das die gute Laune des Abends perfekt einfängt.' },
  { cat: 'Die Stimmung', text: 'Macht ein „Geheimagent“-Foto – cool, lässig, mit Trinkglas als Requisite.' },
  { cat: 'Die Stimmung', text: 'Stellt gemeinsam eine Filmplakat-Pose nach, dramatisch übertrieben.' },
  { cat: 'Die Stimmung', text: 'Macht ein Foto, das nur Lachfalten zeigt – so nah wie möglich dran.' },
  { cat: 'Die Stimmung', text: 'Baut mit den Händen einen Rahmen und „fotografiert“ eine dritte Person hindurch.' },
  { cat: 'Die Stimmung', text: 'Macht ein Foto, das komplett übertrieben glücklich wirkt – Zähne blitzen lassen.' },
  { cat: 'Die Stimmung', text: 'Stellt eine Zeitlupen-Bewegung nach und friert für das Foto genau mittendrin ein.' },
  { cat: 'Die Stimmung', text: 'Macht ein Model-Shooting-Foto – ernster Blick, eine Hand in der Hüfte.' },
  { cat: 'Die Stimmung', text: 'Findet die schrägste Pose, die euch spontan einfällt, und haltet sie für die Kamera.' },
  { cat: 'Die Stimmung', text: 'Macht ein Foto, das zeigt, wie sehr ihr euch auf den Rest des Abends freut.' },

  // — Die Musik —
  { cat: 'Die Musik', text: 'Finde jemanden, der gerade denselben Ohrwurm im Kopf hat wie du – summt ihn gemeinsam.' },
  { cat: 'Die Musik', text: 'Spielt Luftgitarre zu zweit, so als stündet ihr auf der großen Bühne.' },
  { cat: 'Die Musik', text: 'Finde jemanden, der schon mal auf einem Festival war, und tauscht die beste Konzert-Erinnerung aus.' },
  { cat: 'Die Musik', text: 'Nennt gleichzeitig euren Lieblingssong des Abends – Treffer oder nicht, Foto dazu.' },
  { cat: 'Die Musik', text: 'Stellt ein Album-Cover eurer Lieblingsband nach.' },
  { cat: 'Die Musik', text: 'Finde jemanden und tanzt eine Sekunde lang wild, bevor die Kamera klickt.' },
  { cat: 'Die Musik', text: 'Macht ein Foto, als wärt ihr eine Boygroup beim großen Gruppenfoto.' },
  { cat: 'Die Musik', text: 'Finde die Person mit dem besten Tanzmove des Abends und lernt ihn kurz.' },
  { cat: 'Die Musik', text: 'Lip-syncet gemeinsam eine Songzeile für die Kamera.' },
  { cat: 'Die Musik', text: 'Finde jemanden, der Karaoke liebt, und haltet einen imaginären Mikro-Moment fest.' },
  { cat: 'Die Musik', text: 'Findet die Person, die am längsten schon Musik macht oder gemacht hat, und feiert das im Bild.' },
  { cat: 'Die Musik', text: 'Macht ein Foto mitten in einer spontanen Polonaise.' },
  { cat: 'Die Musik', text: 'Findet zwei Leute mit gegensätzlichem Musikgeschmack und lasst sie sich die Hand geben – Waffenstillstand fürs Foto.' },
  { cat: 'Die Musik', text: 'Stellt eine Rockstar-Landung nach – Sprung, imaginäre Gitarre, große Geste.' },
  { cat: 'Die Musik', text: 'Finde jemanden, der schon mal in einem Chor oder einer Band war, und fragt nach der besten Bühnen-Erinnerung.' },

  // — Das Spiel —
  { cat: 'Das Spiel', text: 'Macht einen Stein-Schere-Papier-Wettkampf – haltet den Siegermoment fest.' },
  { cat: 'Das Spiel', text: 'Balanciert einen Löffel auf der Nase, so lange es geht – Foto vom Versuch.' },
  { cat: 'Das Spiel', text: 'Macht einen Blickkontakt-Wettbewerb – wer zuerst lacht, verliert. Foto vom Moment des Lachens.' },
  { cat: 'Das Spiel', text: 'Spielt kurz Armdrücken (fair und vorsichtig!) und haltet den Einsatz fest.' },
  { cat: 'Das Spiel', text: 'Macht ein Foto von einem spontanen Daumenkrieg (Thumb War).' },
  { cat: 'Das Spiel', text: 'Stellt eine Standbild-Challenge: Wer kann am längsten in einer lustigen Pose einfrieren?' },
  { cat: 'Das Spiel', text: 'Spielt „Wer lacht zuerst“ zu zweit – Kamera bereit für den Verlierer-Moment.' },
  { cat: 'Das Spiel', text: 'Macht ein Foto von einem improvisierten Tauziehen mit einem Schal oder Gürtel.' },
  { cat: 'Das Spiel', text: 'Spielt kurz Schnick-Schnack-Schnuck um den letzten Snack auf dem Teller.' },
  { cat: 'Das Spiel', text: 'Baut gemeinsam einen möglichst hohen Turm aus Bierdeckeln oder Servietten und fotografiert ihn, bevor er umfällt.' },
  { cat: 'Das Spiel', text: 'Spielt eine Runde Fingerhakeln (sanft!) und haltet den Sieger fest.' },
  { cat: 'Das Spiel', text: 'Versucht zu zweit, ohne Hände ein Stück Papier weiterzugeben – Foto vom Versuch.' },
  { cat: 'Das Spiel', text: 'Macht einen spontanen Grimassen-Wettbewerb – wer die lustigste Fratze zieht, gewinnt.' },
  { cat: 'Das Spiel', text: 'Spielt kurz Blinde Kuh mit verbundenen Augen (ein Schal reicht) – haltet die Verwirrung fest.' },
  { cat: 'Das Spiel', text: 'Baut mit den Händen ein Schatten-Tier an der Wand und fotografiert den Schatten mit euch.' },

  // — Der Ort —
  { cat: 'Der Ort', text: 'Findet den lautesten Ort der Party und macht dort ein Foto mit zugehaltenen Ohren.' },
  { cat: 'Der Ort', text: 'Findet den ruhigsten Fleck der Location und genießt dort kurz die Stille – Foto dazu.' },
  { cat: 'Der Ort', text: 'Macht ein Foto direkt vor der Musikanlage oder dem DJ-Pult.' },
  { cat: 'Der Ort', text: 'Findet den höchsten Punkt der Location (Treppe, Bühne, Stufe) und posiert von oben.' },
  { cat: 'Der Ort', text: 'Macht ein Foto direkt am Eingang – als Willkommensgruß für später.' },
  { cat: 'Der Ort', text: 'Findet die schönste Aussicht (Fenster, draußen, Balkon) und haltet sie mit Menschen davor fest.' },
  { cat: 'Der Ort', text: 'Macht ein Foto direkt neben der Tanzfläche, bevor ihr selbst tanzt.' },
  { cat: 'Der Ort', text: 'Findet den Ort mit dem besten Essen und posiert stolz davor.' },
  { cat: 'Der Ort', text: 'Macht ein Foto am Getränketisch – Prost auf die Location!' },
  { cat: 'Der Ort', text: 'Findet eine Ecke, die noch niemand fotografiert hat, und macht das erste Bild dort.' },
  { cat: 'Der Ort', text: 'Macht ein Foto direkt unter einer Lichterkette oder einem Deko-Element an der Decke.' },
  { cat: 'Der Ort', text: 'Findet den gemütlichsten Sitzbereich und macht dort ein entspanntes Gruppenfoto.' },
  { cat: 'Der Ort', text: 'Macht ein Foto draußen, falls möglich – frische Luft, freie Sicht.' },
  { cat: 'Der Ort', text: 'Findet den Ort, an dem heute schon am meisten gelacht wurde, und fragt kurz warum.' },
  { cat: 'Der Ort', text: 'Macht ein Foto direkt vor der Kuchen- oder Dessert-Station.' },
  { cat: 'Der Ort', text: 'Findet den Ort, den ihr euch für den Rest des Abends als Stammplatz aussucht, und markiert ihn mit einem Foto.' },
];

export function taskById(id) {
  return TASKS[id] ? { id, ...TASKS[id] } : null;
}

export function taskCount() {
  return TASKS.length;
}
